config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands do #nesting can only happon on single band
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destory, :edit, :show, :update, :destory] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :destory, :edit, :show, :update, :destory]

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  band_id        :integer          not null
#  title          :string           not null
#  year           :integer          not null
#  recording_type :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ActiveRecord::Base
  validates :band_id, :title, presence: true

  belongs_to :band

  has_many :tracks,
  dependent: :destroy

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums,
  dependent: :destroy

  has_many :tracks,
  through: :albums,
  source: :tracks

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  track_type :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  validates :album_id, :title, :track_type, presence: true

  belongs_to :album

  has_many :band,
  through: :album,
  source: :band

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :name, :password_digest,:email, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6}, allow_nil: true

  before_validation :ensure_session_token

  attr_reader :password

  def self.find_by_credientials(email, password)
    user = User.find_by(email: email)
    (user.nil? || !user.is_password?(password)) ? nil : user
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @band_id = params[:band_id]
    @bands = Band.all.order(:name)
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:error] = @album.errors.full_messages
      redirect_to new_band_album_url(@album.band_id)
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def edit
    @album = Album.find_by(id: params[:id])
    redner :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:error] = @album.errors.full_messages
      redirect_to edit_album_url
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    if @album.destroy
      redirect_to band_url(@album.band_id)
    else
      flash.now[:error] = "Album is indestructable!"
    end
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :recording_type, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    @current_user = user #@ because you are setting instance variable
    session[:session_token] = current_user.session_token
  end

  def logout
    @current_user = nil
    session[:session_token] = ""
  end

  def logged_in?
    current_user == user
  end

  def logged_out?
    current_user != user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all.order(:name)
    render :index
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:error] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:error] = @band.errors.full_messages
      redirect_to edit_band_url
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    if @band.destroy
      redirect_to bands_url
    else
      flash.now[:error] = "Band is indestructable!"
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    email, password = session_params.values
    @user = User.find_by_credientials(email, password)

    if @user
      login(@user)
      redirect_to user_url(current_user)
      # render "users/show"
    else
      flash[:error] = "Invalid username/password."
      redirect_to new_session_url
    end
  end

  def destroy
    current_user.reset_session_token!
    logout
    redirect_to new_session_url
  end

  private

  def session_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def show
    render :show
  end

  def self.login
    super
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/albums/_album_form.html.erb
<% if action == :create %>
  <% form_value_band = @bands.find_by(id: @band_id).name %>
  <% form_value_title = "" %>
  <% form_value_year = "" %>
  <% form_value_rt = "" %>
  <% form_action = albums_url %>
<% elsif action == :update %>
  <% form_value_band = @album.band.name %>
  <% form_value_ = @album.title %>
  <% form_value_name = @album.year %>
  <% form_value_rt = @album.recording_type %>
  <% form_action = album_url(@album) %>
<% end %>

<%= render 'shared/flash' %>

  <form action=" <%= form_action %>" method="POST">
    <%= render 'shared/auth' %>
    <% if action == :update %>
      <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="album_band_id">Band: </label>
    <select id="album_band_id" name="album[band_id]">
      <option></option>
      <% @bands.each do |band| %>
        <option
          <%= band.name == form_value_band ? "selected" : "" %>
          value="<%= band.id %>" ><%= band.name %>
        </option>
      <% end %>
    </select>

    <label for="album_title">Title: </label>
    <input id ="album_title" type="text" name="album[title]" value="<%= form_value_title %>">
    <label for="album_year">Year: </label>
    <input id ="album_year" type="text" name="album[year]" value="<%= form_value_year %>">
    <label for="album_rt">Recording Type: </label>
    <input id="album_rt" type="radio" name="album[recording_type]" value="studio">
    <label for="album_rt">Studio </label>
    <input id="album_rt" type="radio" name="album[recording_type]" value="live">
    <label for="album_rt">Live </label>




  <%= render 'shared/submit' %>

  </form>

app/views/albums/new.html.erb
<%= render 'shared/back', main: :band_from_new %>

<h1>NEW ALBUM!</h1>

<%= render 'album_form', action: :create %>

app/views/albums/show.html.erb
<%= render 'shared/back', main: :band_from_show %>
<h1> <%=@album.band.name %> </h1>

<h3> Title: <%= @album.title %> </h3>
<h3> Years: <%= @album.year %> </h3>
<h3> Recording Type: <%= @album.recording_type.capitalize %> </h3>
<h3> Tracks:</h3>
  <ol>
    <% @album.tracks.each do |track| %>
      <li><%= track.title %> (<%=track.track_type%>)</li>
    <% end %>
  </ol>

app/views/bands/_album.html.erb
<%= album.title %>

app/views/bands/_band.html.erb
<%if action == :index%>
  <%= link_to band.name, band_url(band.id)  %>
<% end %>
<ul>
  <% band.albums.order(:year).each do |album| %>
  <li><%= link_to "#{album.title}", album_url(album.id) %> </li>
  <% end %>
</ul>

<% if action == :show %>
  <%= button_to "Add New Album", new_band_album_url(band.id), method: :get %>
  <%= button_to "Edit Band", edit_band_url(band.id), method: :get %>
  <%= button_to "Delete Band", band_url(band.id), method: :delete %>

<% end %>
<br><br>

app/views/bands/_band_form.html.erb
<% if action == :create %>
  <% form_value = "" %>
  <% form_action = bands_url %>
<% elsif action == :update %>
  <% form_value = @band.name %>
  <% form_action = band_url %>
<% end %>

<%= render 'shared/flash' %>

  <form action=" <%= form_action %>" method="POST">
    <%= render 'shared/auth' %>
    <% if action == :update %>
      <input type="hidden" name="_method" value="PATCH">
    <% end %>
    <label for="band_name">Band Name: </label>
    <input id ="band_name" type="text" name="band[name]" value="<%= form_value %>">

  <%= render 'shared/submit' %>

  </form>

app/views/bands/edit.html.erb
<%= render 'shared/back', main: :bands %>
<h1>EDIT!</h1>

<%= render 'band_form', action: :update %>

app/views/bands/index.html.erb
<h1>BANDS!</h1>


<%= render @bands, action: :index %>

<%= button_to "Add New Band", new_band_url, method: :get %>

app/views/bands/new.html.erb
<%= render 'shared/back', main: :bands %>

<h1>NEW!</h1>

<%= render 'band_form', action: :create %>

app/views/bands/show.html.erb
<%= render 'shared/back', main: :bands %>
<h1><%= @band.name %></h1>
<h3>Albums: </h3>
<%= render @band, action: :show %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= render 'shared/button', action: :logout %>
  <% else %>
    <%= render 'shared/button', action: :signup %>
    <%= render 'shared/button', action: :login %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/shared/_auth.html.erb
<input type="hidden" name="authenticity_token" value="form_authenticity_token">

app/views/shared/_back.html.erb
<% if main == :bands %>
  <% link_name = main %>
  <% link_url = bands_url %>
<% elsif main == :band_from_show %>
  <% link_name = @album.band.name %>
  <% link_url = band_url(@album.band_id) %>
<% elsif main == :band_from_new %>
  <% link_name = Album.find_by(band_id: params[:band_id]).band.name %>
  <% link_url = band_url(params[:band_id]) %>
<% elsif main == :album %>
  <% link_name = @album.name %>
  <% link_url = band_url(@album) %>
<% end %>


<br>
<%= link_to "<<back to #{link_name}", link_url %>
<br>

app/views/shared/_button.html.erb
<% if action == :signup %>
  <% form_action = new_user_url %>
  <% form_method = "GET" %>
  <% form_value = "SIGN UP" %>

<% elsif action == :login %>
  <% form_action = new_session_url %>
  <% form_method = "GET" %>
  <% form_value = "LOGIN" %>

<% elsif action == :logout %>
  <% form_action = session_url %>
  <% form_method = "POST" %>
  <% form_value = "LOGOUT" %>
<% end %>


<form action=" <%= form_action %>" method= "<%= form_method %>">
  <%= render 'shared/auth' %>
  <% if action == :logout %>
    <input type="hidden" name="_method" value="DELETE">
  <% end %>
  <input type="submit" value=" <%= form_value %>">
</form>

app/views/shared/_flash.html.erb
<% if flash %>
  <% flash.each do |error| %>
    <%= error.flatten.first.capitalize  %>:   <%= error.flatten.last  %>
  <% end %>
  <br><br>
<% end %>

app/views/shared/_form.html.erb
<% if action == :create_account %>
  <% form_action = users_url %>
<% elsif action == :login %>
  <% form_action = session_url %>
<% end %>


<form action=" <%= form_action %>" method="POST">
  <%= render 'shared/auth' %>
  <% if action == :create_account %>
  <label for="user_name">Name: </label>
    <input id= "user_name" type="text" name="user[name]">
  <% end %>

<br>

<label for="user_email">Email: </label>
  <input id= "user_email" type="text" name="user[email]">

<br>

<label for="user_password">Password: </label>
  <input id= "user_password" type="password" name="user[password]">

<input type="submit" value="Submit">

</form>

app/views/shared/_submit.html.erb
<input type="submit" value="Submit">
<br><br>

app/views/users/new.html.erb
<h1>CREATE AN ACCOUNT</h1>

<%= render 'shared/flash' %>

<%= render 'shared/form', action: :create_account %>

app/views/users/show.html.erb
<h1>Hello, <%= current_user.name %> ! </h1>